# Generated by Django 4.2.30 on 2026-06-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
