# Generated by Django 4.2.30 on 2026-06-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='KnowledgeDocument',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UploadedProject',
        ),
        migrations.DeleteModel(
            name='UserMemory',
        ),
    ]
