# Generated by Django 4.2.30 on 2026-06-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeBase',
            new_name='Knowledge',
        ),
    ]
